### ISSUE TITLE
乱点出一个bug

### ISSUE THREAD

**Issue by hustcc** [amibug/fly#6]
readme中的demo：
![image](https://cloud.githubusercontent.com/assets/7856674/16075976/cc04c102-3323-11e6-8a69-aa657c3d7ed6.png)

一直点购物车点的下面，结果成这样了。

**Comment by hustcc** [comment]
再来一张详细一点的：
![image](https://cloud.githubusercontent.com/assets/7856674/16076020/fd44c7ee-3323-11e6-8e78-da923a86f1b5.png)

应该是坐标计算的时候，中间值被多次处理，导致异常，其中图片中红色框那里是点击位置，但是小人不是从那个地方出来的。

**Comment by parkyang** [comment]
应该是由于fixed导致的！
