### ISSUE TITLE
destroy方法 未定义

### ISSUE THREAD

**Issue by Christian-L** [amibug/fly#8]
VM4079:17 Uncaught TypeError: flyer.destroy is not a function
![505a tmp](https://cloud.githubusercontent.com/assets/8042746/16616044/336a09e4-43ad-11e6-946a-f65abdb59417.jpg)

**Comment by xuqisheng** [comment]
请教下，我报同样的错，是什么原因？

**Comment by Christian-L** [comment]
flyer.destroy();换成this.destory();就好了
